services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - APP_ENV=production
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
