apiVersion: apps/v1

kind: Deployment

metadata:
  name: fastapi

spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-app:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          env:
            - name: APP_ENV
              value: "production"


