name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-httpx prometheus-fastapi-instrumentator
      - name: Run tests
        run: pytest test_main.py -v
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t fastapi-app:latest .
  validate-k8s:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status
      
      - name: Validate Kubernetes manifests
        run: |
         for file in prometheus-service.yml *.yaml; do 
           [ -e "$file" ] || continue
           if kubectl create -f "file" > /dev/null 2>&1; then
             echo "created new resource from $file"
           else
             echo "Already exists. Updating..."
             kubectl apply -f "$file" --dry-run=client 
           fi
         done
